basePath: /api/v1
definitions:
  handler.forgotPasswordReq:
    properties:
      email:
        type: string
    required:
    - email
    type: object
  handler.loginReq:
    properties:
      email:
        type: string
      password:
        type: string
    required:
    - email
    - password
    type: object
  handler.registerReq:
    properties:
      email:
        type: string
      password:
        minLength: 6
        type: string
      passwordConfirm:
        minLength: 6
        type: string
    required:
    - email
    - password
    - passwordConfirm
    type: object
  handler.resendEmailVerificationReq:
    properties:
      email:
        type: string
    required:
    - email
    type: object
  handler.resetPasswordReq:
    properties:
      code:
        type: string
      password:
        minLength: 6
        type: string
      passwordConfirm:
        minLength: 6
        type: string
    required:
    - code
    - password
    - passwordConfirm
    type: object
  handler.updateUserReq:
    properties:
      avatar_url:
        type: string
      current_password:
        minLength: 6
        type: string
      email:
        type: string
      new_password:
        minLength: 6
        type: string
    type: object
  handler.verifyEmailReq:
    properties:
      code:
        type: string
    type: object
  models.User:
    properties:
      avatar_url:
        type: string
      created_at:
        type: string
      email:
        type: string
      id:
        type: string
      is_banned:
        type: boolean
      is_email_verified:
        type: boolean
      role:
        $ref: '#/definitions/models.UserRole'
      updated_at:
        type: string
    type: object
  models.UserRole:
    enum:
    - default
    - admin
    type: string
    x-enum-varnames:
    - RoleDefault
    - RoleAdmin
host: localhost:8080
info:
  contact:
    name: Stanislav Simakhin
    url: https://ssyan.ru
  description: Backend API
  title: Backend API
  version: "1.0"
paths:
  /auth/forgot-password:
    post:
      consumes:
      - application/json
      description: Send code to email
      parameters:
      - description: Forgot password dto
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/handler.forgotPasswordReq'
      produces:
      - application/json
      responses:
        "200":
          description: OK
        "400":
          description: Bad Request
        "404":
          description: Not Found
        "500":
          description: Internal Server Error
      summary: Forgot password
      tags:
      - auth
  /auth/login:
    post:
      consumes:
      - application/json
      description: Login user
      parameters:
      - description: login dto
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/handler.loginReq'
      produces:
      - application/json
      responses:
        "200":
          description: OK
        "401":
          description: Unauthorized
      summary: Login user
      tags:
      - auth
  /auth/logout:
    post:
      consumes:
      - application/json
      description: Logout user
      produces:
      - application/json
      responses:
        "200":
          description: OK
        "401":
          description: Unauthorized
      summary: Logout user
      tags:
      - auth
  /auth/oauth/{provider}:
    get:
      description: Get redirect URL for OAuth provider
      parameters:
      - description: Provider (google/yandex/github)
        in: path
        name: provider
        required: true
        type: string
      responses:
        "302":
          description: Found
      summary: Get OAuth URL
      tags:
      - auth
  /auth/oauth/{provider}/callback:
    get:
      description: Handle OAuth provider callback
      parameters:
      - description: Provider (google, yandex, github)
        in: path
        name: provider
        required: true
        type: string
      - description: OAuth code
        in: query
        name: code
        required: true
        type: string
      responses:
        "200":
          description: OK
      summary: OAuth Callback
      tags:
      - auth
  /auth/refresh:
    post:
      consumes:
      - application/json
      description: Refresh JWT tokens
      produces:
      - application/json
      responses:
        "200":
          description: OK
        "401":
          description: Unauthorized
      summary: Refresh JWT tokens
      tags:
      - auth
  /auth/register:
    post:
      consumes:
      - application/json
      description: Create a new user
      parameters:
      - description: Register dto
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/handler.registerReq'
      produces:
      - application/json
      responses: {}
      summary: Register new user
      tags:
      - auth
  /auth/resend-email-verification:
    post:
      consumes:
      - application/json
      description: Resend email verification code to user email
      parameters:
      - description: Resend email verification dto
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/handler.resendEmailVerificationReq'
      produces:
      - application/json
      responses:
        "200":
          description: OK
        "400":
          description: Bad Request
        "404":
          description: Not Found
        "500":
          description: Internal Server Error
      summary: Resend email verification code
      tags:
      - auth
  /auth/reset-password:
    post:
      consumes:
      - application/json
      description: Reset password via code
      parameters:
      - description: Reset password dto
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/handler.resetPasswordReq'
      produces:
      - application/json
      responses:
        "200":
          description: OK
        "400":
          description: Bad Request
        "500":
          description: Internal Server Error
      summary: Reset password
      tags:
      - auth
  /auth/sessions:
    delete:
      description: Delete all active sessions
      responses:
        "200":
          description: OK
      security:
      - BearerAuth: []
      summary: Delete all sessions
      tags:
      - auth
    get:
      description: Get active sessions
      responses:
        "200":
          description: OK
      security:
      - BearerAuth: []
      summary: Get active sessions
      tags:
      - auth
  /auth/sessions/{sessionId}:
    delete:
      description: Delete session by ID
      parameters:
      - description: Session ID
        in: path
        name: sessionId
        required: true
        type: string
      responses:
        "200":
          description: OK
      security:
      - BearerAuth: []
      summary: Delete session
      tags:
      - auth
  /auth/sessions/{sessionId}/block:
    patch:
      description: Block session by ID
      parameters:
      - description: Session ID
        in: path
        name: sessionId
        required: true
        type: string
      responses:
        "200":
          description: OK
      security:
      - BearerAuth: []
      summary: Block session
      tags:
      - auth
  /auth/verify-email:
    get:
      consumes:
      - application/json
      description: Verify email address using verification code
      parameters:
      - description: Verification code
        in: query
        name: code
        type: string
      - description: Verification code dto
        in: body
        name: request
        schema:
          $ref: '#/definitions/handler.verifyEmailReq'
      produces:
      - application/json
      responses:
        "200":
          description: OK
        "400":
          description: Bad Request
        "500":
          description: Internal Server Error
      summary: Verify email
      tags:
      - auth
    post:
      consumes:
      - application/json
      description: Verify email address using verification code
      parameters:
      - description: Verification code
        in: query
        name: code
        type: string
      - description: Verification code dto
        in: body
        name: request
        schema:
          $ref: '#/definitions/handler.verifyEmailReq'
      produces:
      - application/json
      responses:
        "200":
          description: OK
        "400":
          description: Bad Request
        "500":
          description: Internal Server Error
      summary: Verify email
      tags:
      - auth
  /users/me:
    get:
      consumes:
      - application/json
      description: Get self
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.User'
      security:
      - BearerAuth: []
      summary: Get self
      tags:
      - users
    patch:
      consumes:
      - application/json
      description: Update self
      parameters:
      - description: Update dto
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/handler.updateUserReq'
      produces:
      - application/json
      responses:
        "200":
          description: OK
      security:
      - BearerAuth: []
      summary: Update self
      tags:
      - users
securityDefinitions:
  BearerAuth:
    description: Bearer [JWT]
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
