basePath: /api/v1
host: localhost:8080
info:
  contact:
    name: Stanislav Simakhin
    url: https://ssyan.ru
  description: Backend API
  title: Backend API
  version: "1.0"
paths: {}
securityDefinitions:
  BearerAuth:
    description: Bearer [JWT]
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
